'use client';

import { useEffect } from 'react';
import SecondaryHeader, { BlogPrologue, BulletList, Code, InlineCode, NumberedList, ThirdHeader } from '@/components/BlogComponents';
import BlogTable from '@/components/BlogTable';
import MermaidDiagram from '@/components/MermaidDiagram';
import StyledLink from '@/components/StyledLink';
import TableOfContents from '@/components/TableOfContents';

const codeBlock1 = "flowchart LR\r\n  App[GUI application] --\u003e GDI[gdi32full.dll]\r\n  App --\u003e U[win32u.dll NtUser/NtGdi stubs]\r\n  GDI --\u003e U\r\n  U --\u003e NT[ntoskrnl.exe syscall dispatch]\r\n  NT --\u003e K[win32k.sys service front door]\r\n  K --\u003e F[win32kfull.sys lifecycle layer]\r\n  F --\u003e B[win32kbase.sys shared state]\r\n  B --\u003e RS[win32kbase_rs.sys patch companion]\r\n  B \u003c--\u003e DX[dxgkrnl.sys graphics state]\r\n  DX \u003c--\u003e M1[dxgmms1.sys scheduling path]\r\n  DX \u003c--\u003e M2[dxgmms2.sys memory path]";
const codeBlock2 = "sequenceDiagram\r\n  participant NT as ntoskrnl\r\n  participant Full as win32kfull\r\n  participant Base as win32kbase\r\n  participant Front as win32k.sys\r\n  participant DX as dxgkrnl\r\n  NT-\u003e\u003eFull: session Win32 process callout\r\n  Full-\u003e\u003eBase: AllocateW32ProcessImpl\r\n  Base-\u003e\u003eNT: PsSetProcessWin32Process\r\n  Full-\u003e\u003eBase: USER + GDI + DComposition process callouts\r\n  Base-\u003e\u003eFront: DxDdProcessCallout(W32PROCESS, create)\r\n  Front-\u003e\u003eDX: session graphics-interface process callback\r\n  DX-\u003e\u003eNT: PsSetProcessDxgProcess\r\n  NT-\u003e\u003eFull: session Win32 thread callout\r\n  Full-\u003e\u003eBase: AllocateW32ThreadImpl + thread callbacks\r\n  Base-\u003e\u003eNT: PsSetThreadWin32Thread(wrapper)\r\n  Base-\u003e\u003eFront: DxDdThreadCallout\r\n  Front-\u003e\u003eDX: session graphics-interface thread callback";
const codeBlock3 = "flowchart TD\r\n    A[SYSCALL to KiSystemCall64] --\u003e B[Switch to the kernel stack]\r\n    AS[KVA shadow entry] --\u003e B\r\n    B --\u003e C[Apply mitigations and build the trap frame]\r\n    C --\u003e D[KiSystemServiceUser]\r\n    D --\u003e P{Syscall provider intercepts}\r\n    P -- ordinary --\u003e E[KiSystemServiceStart]\r\n    P -- handled or error --\u003e X[Normal or Pico exit]\r\n    E --\u003e F[Select descriptor and validate index]\r\n    F -- invalid GUI index --\u003e G[PsConvertToGuiThread]\r\n    G -- success --\u003e F\r\n    F -- invalid or failure --\u003e H[Return invalid system service]\r\n    F -- valid --\u003e I[Decode target and argument count]\r\n    I --\u003e J[Optional GDI batch flush]\r\n    J --\u003e K[Copy stack arguments]\r\n    K --\u003e L{Instrumentation mode}\r\n    L -- direct --\u003e M[Call service routine]\r\n    L -- dynamic trace --\u003e N[KiTrack wrapper]\r\n    L -- performance logging --\u003e O[PerfInfo wrapper]\r\n    M --\u003e Q[KiSystemServiceExit]\r\n    N --\u003e Q\r\n    O --\u003e Q\r\n    H --\u003e Q\r\n    Q --\u003e R{Return context}\r\n    R -- kernel caller --\u003e S[Restore trap frame and return]\r\n    R -- user caller --\u003e T[Validate and restore user state]\r\n    T --\u003e U{KVA shadow enabled}\r\n    U -- no --\u003e V[SWAPGS and SYSRET]\r\n    U -- yes --\u003e W[KiKernelSysretExit]\r\n    X --\u003e Y[Pico or IRET exit]";
const codeBlock4 = "NTSTATUS __fastcall PsInvokeWin32Callout(unsigned int calloutId, void *ctx)\r\n{\r\n    if (!PspUpdateCalloutParameters(calloutId, ctx, /* additional callout state */))\r\n    {\r\n        return STATUS_INVALID_PARAMETER;\r\n    }\r\n\r\n    callback = PsSessionGetWin32Callouts();\r\n    callback_reference = ExReferenceCallBackBlock(callback);\r\n\r\n    if (!callback_reference )\r\n    {\r\n        return STATUS_INVALID_PARAMETER;\r\n    }\r\n\r\n    status = guard_dispatch_icall_no_overrides(callback_reference);\r\n    ExDereferenceCallBackBlock(callback, callback_reference);\r\n    return status;\r\n}";
const codeBlock5 = "EX_CALLBACK* PsSessionGetWin32Callouts()\r\n{\r\n    if ((KeGetCurrentThread()-\u003eApcState.Process.Flags \u0026 OverrideAddressSpace) == 0 )\r\n    {\r\n        return \u0026PsWin32CallBack;\r\n    }\r\n\r\n    bool win32CalloutsAvailable = KeGetCurrentThread()-\u003eApcState.Process.Session-\u003eWin32Callouts;\r\n\r\n    if (!win32CalloutsAvailable )\r\n    {\r\n        return \u0026PsWin32NullCallBack;\r\n    }\r\n\r\n    return \u0026PsWin32CallBack;\r\n}";

export default function PostPaintItBlueReverseWin32k() {
    useEffect(() => {
        document.title = "Paint It Blue: Reversing Win32k's Callbacks";
    }, []);

    return (
        <div className="card-surface rounded-xl p-6 lg:p-8 animate-fade-in post-content">
            <BlogPrologue title={"Paint It Blue: Reversing Win32k's Callbacks"} date={"28.09.2026"} projectLink={"https://github.com/Idov31"} />
            <div className="pt-4">
                <article>
                    <TableOfContents />
                    <SecondaryHeader text={"Prologue"} />
                    <div className="pt-4">{"I started this research while looking for a new PatchGuard bypass technique. That lead did not produce a bypass, but it pushed me into a part of Windows that is often mentioned without explaining its basics: how Win32k is split across modules, how an x64 GUI syscall reaches it, and how the kernel chooses the callback used for session-aware Win32 operations."}</div>
                    <div className="pt-4">{"We will follow the path from "}<InlineCode text={"win32u.dll"} />{" to "}<InlineCode text={"KiSystemCall64"} />{", look at how a thread becomes a GUI thread, and then focus on "}<InlineCode text={"PsInvokeWin32Callout"} />{", "}<InlineCode text={"PsWin32CallBack"} />{", and "}<InlineCode text={"PsWin32NullCallBack"} />{"."}</div>
                    <div className="pt-4">{"Without further ado, grab your coffee, tea, or your favorite drink, and let's dive into Win32k."}</div>
                    <SecondaryHeader text={"The Win32k Subsystem"} />
                    <ThirdHeader text={"Intro"} />
                    <div className="pt-4">{"The Win32k subsystem implements much of the kernel side of the Windows graphical user interface (GUI), including user, GDI, composition, and graphics-facing services. User-mode applications reach those services through syscalls. Despite how central the subsystem is, public discussion often jumps directly to a new vulnerability in "}<InlineCode text={"xxxWinSomeBizzareFunctionThatIsResponsibleForASinglePixel"} />{" or to a short reference in the Windows Internals books. The ordinary control flow receives much less attention."}</div>
                    <div className="pt-4">{"The name Win32k makes it sound like one component, but the modern implementation is split across several kernel modules and user-mode libraries. "}<InlineCode text={"win32k.sys"} />{" provides the service and session-facing front door, "}<InlineCode text={"win32kbase.sys"} />{" owns much of the shared USER, GDI, and composition state, and "}<InlineCode text={"win32kfull.sys"} />{" coordinates higher-level services and lifecycle callouts. The graphics process and thread objects live in the DXG stack, while "}<InlineCode text={"ntoskrnl.exe"} />{" owns the executive process, thread, and session links that connect everything together. In user mode, applications usually reach this machinery through "}<InlineCode text={"gdi32full.dll"} />{" and the "}<InlineCode text={"NtUser*"} />{" or "}<InlineCode text={"NtGdi*"} />{" syscall stubs exported by "}<InlineCode text={"win32u.dll"} />{"."}</div>
                    <div className="pt-4">{"This split becomes especially important when looking at Win32k-related syscalls, or \"GUI syscalls\" in less formal terms. Their user-mode stubs enter the same kernel syscall dispatcher as ordinary native services. The difference is in how the service number selects the Win32k descriptor table and in the extra work Windows may perform to convert a regular thread into a GUI thread before dispatch can continue."}</div>
                    <ThirdHeader text={"Win32k Architecture"} />
                    <MermaidDiagram definition={codeBlock1} caption={"Win32k component and call-flow overview"} />
                    <div className="pt-4">{"At a high level, there are two related paths to keep in mind: the service-call path and the GUI-state lifecycle path. They meet inside the same subsystem, but they solve different problems. The service-call path finds and invokes an "}<InlineCode text={"NtUser*"} />{" or "}<InlineCode text={"NtGdi*"} />{" implementation. The lifecycle path creates the process and thread state that lets those services operate safely in the correct session."}</div>
                    <div className="pt-4">{"For a typical service call, a GUI application calls a USER or GDI API. GDI wrappers in "}<InlineCode text={"gdi32full.dll"} />{" eventually reach an imported function in "}<InlineCode text={"win32u.dll"} />{", while many USER operations call a "}<InlineCode text={"win32u.dll"} />{" stub directly. On the normal x64 path covered here, the stub places a build-specific service number in "}<InlineCode text={"EAX"} />{", copies the first argument into "}<InlineCode text={"R10"} />{" to preserve the Windows x64 calling convention across "}<InlineCode text={"SYSCALL"} />{", and enters the kernel. The analyzed stubs can also select the legacy "}<InlineCode text={"int 2e"} />{" path according to a flag in shared user data, but that compatibility entry is outside this post's scope. "}<InlineCode text={"ntoskrnl.exe"} />{" then decodes the service number and selects either the native service table or the Win32k service table. A valid Win32k entry resolves to code exposed through the Win32k module set."}</div>
                    <div className="pt-4">{"The main components in that path have distinct responsibilities:"}</div>
                    <BulletList items={[{ content: <><InlineCode text={"win32u.dll"} />{" contains the user-mode "}<InlineCode text={"NtUser*"} />{" and "}<InlineCode text={"NtGdi*"} />{" syscall stubs."}</> }, { content: <><InlineCode text={"gdi32full.dll"} />{" implements and wraps user-mode GDI functionality before calling those stubs."}</> }, { content: <><InlineCode text={"ntoskrnl.exe"} />{" performs syscall dispatch, owns the executive process and thread fields, and initiates GUI-thread conversion when it is needed."}</> }, { content: <><InlineCode text={"win32k.sys"} />{" is the syscall and session-facing front door. It exposes service-table information and dispatches through session-local Win32k and graphics interfaces."}</> }, { content: <><InlineCode text={"win32kbase.sys"} />{" allocates and manages much of the shared Win32 process and thread state and runs USER, GDI, and DirectComposition setup and teardown."}</> }, { content: <><InlineCode text={"win32kfull.sys"} />{" orchestrates the upper process and thread callout chains and supplies higher-level USER and GDI services."}</> }, { content: <><InlineCode text={"win32kbase_rs.sys"} />{" is a Rust patch companion that uses exports and allocators from the base module. Its presence does not mean every GUI entry passes through it."}</> }, { content: <><InlineCode text={"dxgkrnl.sys"} />{", together with "}<InlineCode text={"dxgmms1.sys"} />{" and "}<InlineCode text={"dxgmms2.sys"} />{", owns the graphics-facing process, thread, scheduling, and video-memory state used by Win32k."}</> }]} />
                    <div className="pt-4">{"The lifecycle path begins in the executive rather than in a user-mode syscall stub. "}<InlineCode text={"PsConvertToGuiThread"} />{" checks whether the current process and thread already have GUI state and whether policy allows conversion. It obtains the Win32 callouts associated with the current session, initializes process state when necessary, invokes the thread callout, and rolls back the relevant flags if thread initialization fails. The process conversion can therefore involve both a process callout and a thread callout, even though the immediate goal is to make one thread capable of issuing GUI services."}</div>
                    <div className="pt-4"><InlineCode text={"win32kfull.sys"} />{" coordinates these lifecycle callbacks. On the ordinary creation path, it asks "}<InlineCode text={"win32kbase.sys"} />{" to allocate the Win32 process object and then runs the USER, GDI, and DirectComposition process callbacks. The GDI branch crosses through the session graphics interface into "}<InlineCode text={"dxgkrnl.sys"} />{", which creates or reuses its own graphics process object. Thread creation follows a similar chain for Win32k and DXG thread state. Teardown unwinds these relationships, although the exact order can vary by event and branch."}</div>
                    <div className="pt-4">{"It is useful to separate ownership from storage. The executive owns fields in "}<InlineCode text={"EPROCESS"} />{" and "}<InlineCode text={"ETHREAD"} />{"/"}<InlineCode text={"KTHREAD"} />{", but some of those fields point to objects managed by Win32k or DXG. The process's "}<InlineCode text={"Win32Process"} />{" slot points into Win32k-managed process state, while "}<InlineCode text={"DxgProcess"} />{" points to a graphics object managed by DXG. The "}<InlineCode text={"Session"} />{" pointer selects the session-private callbacks and interfaces used along the way; it is not itself either of those process objects."}</div>
                    <div className="pt-4">{"The thread side has another subtlety. The executive's Win32 thread slot does not point directly to a "}<InlineCode text={"THREADINFO"} />{". "}<InlineCode text={"win32kbase.sys"} />{" allocates a small wrapper, stores the "}<InlineCode text={"THREADINFO"} />{" pointer inside it, and installs that wrapper in the executive slot. Win32k accessors dereference the wrapper when they need the underlying USER thread state. Some accessors also verify that an attached process belongs to the same session before returning it, which prevents session-private GUI state from being used through the wrong process context."}</div>
                    <div className="pt-4">{"This session boundary is present throughout the architecture. Win32k selects service callbacks and graphics interfaces using the current process's session, so a GUI pointer by itself is not enough to describe the active environment. It also explains why "}<InlineCode text={"PsWin32CallBack"} />{", "}<InlineCode text={"PsWin32NullCallBack"} />{", and "}<InlineCode text={"PsSessionGetWin32Callouts"} />{" matter later in this post: they sit on the executive-to-session boundary rather than being ordinary syscall implementations."}</div>
                    <div className="pt-4">{"These relationships were recovered through static analysis of a Windows 11 build cohort. Function names and the broad architecture are useful for understanding the design, but internal field offsets, service numbers, module splits, and rare branch behavior are build-specific and should be revalidated before being used against another kernel."}</div>
                    <ThirdHeader text={"Different Types of Processes and Threads"} />
                    <MermaidDiagram definition={codeBlock2} caption={"Normal creation path for Win32k and DXG process and thread state"} />
                    <div className="pt-4">{"The diagram shows the normal creation path for both process-wide and thread-specific GUI state. The process path starts when "}<InlineCode text={"ntoskrnl.exe"} />{" invokes the Win32 process callout registered for the current session. "}<InlineCode text={"win32kfull.sys"} />{" coordinates the operation, while "}<InlineCode text={"win32kbase.sys"} />{" allocates the Win32 process object and publishes it back through the executive's "}<InlineCode text={"Win32Process"} />{" slot. USER, GDI, and DirectComposition can then initialize their own portions of that object."}</div>
                    <div className="pt-4">{"The GDI branch continues into "}<InlineCode text={"win32k.sys"} />{", which uses the session's graphics interface to reach "}<InlineCode text={"dxgkrnl.sys"} />{". DXG creates the graphics process object and publishes it through the executive's separate "}<InlineCode text={"DxgProcess"} />{" slot. These two slots refer to state owned by different subsystems: "}<InlineCode text={"Win32Process"} />{" belongs to the Win32k lifecycle, while "}<InlineCode text={"DxgProcess"} />{" belongs to the graphics kernel. They cooperate, but they are not interchangeable."}</div>
                    <div className="pt-4">{"The thread path follows the same division of responsibility. "}<InlineCode text={"win32kfull.sys"} />{" asks "}<InlineCode text={"win32kbase.sys"} />{" to allocate the Win32 thread wrapper and run the thread callbacks. The wrapper is stored in the executive thread slot and points to the underlying "}<InlineCode text={"THREADINFO"} />{"; the slot is not a direct "}<InlineCode text={"THREADINFO"} />{" pointer. The GDI thread callback then crosses the session graphics interface so DXG can establish its corresponding graphics thread state. The diagram focuses on creation. Teardown reverses these ownership relationships, although the exact callback order can differ between branches."}</div>
                    <div className="pt-4">{"We can divide processes into two broad states for this discussion: processes that have initialized Win32k state and processes that have not. This distinction is important because GUI processes interact with session-private Win32k objects to manage windows and graphical elements. A process without that state is not necessarily permanently unable to make GUI-related syscalls; its first suitable Win32k service can cause Windows to convert the calling thread and initialize the required process state. Policy can still prohibit that conversion or block the syscall entirely."}</div>
                    <div className="pt-4">{"Two useful signals when investigating whether that path is available are:"}</div>
                    <BulletList items={[{ content: <><InlineCode text={"MitigationFlags"} />{" in "}<InlineCode text={"EPROCESS"} />{" that disallow GUI-related syscalls (specifically "}<InlineCode text={"DisallowWin32kSystemCalls"} />{")."}</> }, { content: <>{"Whether the thread is a GUI thread, which can be determined by checking the "}<InlineCode text={"KTHREAD"} />{" structure's "}<InlineCode text={"ThreadFlags"} />{" and "}<InlineCode text={"GuiThread"} />{" fields."}</> }]} />
                    <div className="pt-4">{"There are other useful indicators, such as the process's "}<InlineCode text={"Win32Process"} />{", "}<InlineCode text={"Win32KFilterSet"} />{", and "}<InlineCode text={"DxgProcess"} />{" fields, as well as the session's Win32 callout state. These fields do not all describe the same object or share the same owner. The important point is that GUI capability emerges from a coordinated process, thread, graphics, and session setup rather than from one definitive pointer or flag."}</div>
                    <SecondaryHeader text={"Syscalls In Depth"} />
                    <div className="pt-4">{"If you are unfamiliar with the concept of syscalls, please stop, "}<StyledLink href={"https://wiki.osdev.org/System_Calls"} content={"read about them"} textSize="text-md" />{" and then continue."}</div>
                    <div className="pt-4"><InlineCode text={"KiSystemCall64"} />{" is the common 64-bit Windows syscall entry and dispatcher. During processor initialization, Windows places either "}<InlineCode text={"KiSystemCall64"} />{" or the KVA-shadow entry in the "}<InlineCode text={"IA32_LSTAR"} />{" model-specific register. There are no normal callers of the top-level entrypoint. When user mode executes "}<InlineCode text={"SYSCALL"} />{", the processor loads the kernel instruction pointer from "}<InlineCode text={"IA32_LSTAR"} />{" and arrives with a small but important register contract."}</div>
                    <div className="pt-4">{"At entry, "}<InlineCode text={"RAX"} />{" contains the encoded service number, "}<InlineCode text={"RCX"} />{" contains the user return address, and "}<InlineCode text={"R11"} />{" contains the user's flags. "}<InlineCode text={"RSP"} />{" still points to the user stack because "}<InlineCode text={"SYSCALL"} />{" does not switch stacks by itself. The user-mode stub has already copied the first function argument from "}<InlineCode text={"RCX"} />{" to "}<InlineCode text={"R10"} />{"; the second through fourth arguments remain in "}<InlineCode text={"RDX"} />{", "}<InlineCode text={"R8"} />{", and "}<InlineCode text={"R9"} />{", and any remaining arguments are on the user stack."}</div>
                    <ThirdHeader text={"Overview of the Syscall Entry Path"} />
                    <MermaidDiagram definition={codeBlock3} caption={"KiSystemCall64 dispatch and return flow"} />
                    <ThirdHeader text={"Entering the Kernel"} />
                    <div className="pt-4">{"The direct entry begins with "}<InlineCode text={"SWAPGS"} />{", which changes the GS base from user state to the processor's kernel control region. Windows saves the user stack pointer, selects the kernel stack, and creates a synthetic return frame containing the user stack, flags, code segment, and return address. It then expands that state into a trap frame and saves the volatile general-purpose, SIMD, and control state needed to call an ordinary kernel function and later return to user mode."}</div>
                    <div className="pt-4">{"The entry path also applies the mitigations configured for the processor and kernel. Depending on the system, this can include speculation-control MSR updates, return-stack prediction refilling, branch-history-buffer flushing, SMAP access control, and CET shadow-stack transitions. A KVA-shadow entry performs the additional address-space transition before joining the common dispatcher. The exact flags that select these paths are deliberately omitted here because their meanings and locations are build-specific."}</div>
                    <div className="pt-4">{"Once the architectural transition is complete, Windows records thread-visible syscall state. The active trap frame, previous processor mode, original service number, and first argument are associated with the current thread. An optional syscall-provider hook can handle or reject the call before ordinary table dispatch. If it does not, execution continues into the common service dispatcher."}</div>
                    <ThirdHeader text={"Selecting a Service"} />
                    <div className="pt-4">{"The dispatcher separates the encoded service number into a table selector and a service index. In the analyzed kernel, bit 12 selects the second descriptor slot used for Win32k services, while the low 12 bits select an entry within that table."}</div>
                    <div className="pt-4">{"For a Win32k-capable thread, the relevant descriptor array is "}<InlineCode text={"KeServiceDescriptorTableShadow"} />{", commonly called the shadow SSDT. Despite the name, it is not a duplicate used only as a fallback. Its first descriptor represents the native NT services, while its second descriptor exposes the Win32k "}<InlineCode text={"NtUser*"} />{" and "}<InlineCode text={"NtGdi*"} />{" table. Thread state selects the shadow descriptor array, and service-number bit 12 selects its Win32k descriptor. A filtered variant can be selected when Win32k syscall filtering is active. Each chosen descriptor ultimately supplies a service-table base and the number of valid entries."}</div>
                    <div className="pt-4">{"The word \"shadow\" here is unrelated to the KVA-shadow syscall entry described earlier. KVA shadowing controls the address-space transition around kernel entry and exit; "}<InlineCode text={"KeServiceDescriptorTableShadow"} />{" controls which service descriptors are available during dispatch."}</div>
                    <div className="pt-4">{"If the index is valid, Windows reads the corresponding 32-bit SSDT entry. The entry is not a direct function pointer. Its signed upper bits encode the service target relative to the table base, while the low nibble records how many additional arguments must be copied from the caller's stack. This compact representation lets the dispatcher recover both the destination and the calling requirements from one value."}</div>
                    <div className="pt-4">{"For stack arguments, the dispatcher reserves enough kernel stack space for the supported maximum and copies only the number encoded in the entry. User-mode source addresses are constrained by the user probe boundary so that an invalid or kernel-space address faults through the syscall exception path rather than becoming an unrestricted kernel read. The copy is implemented as an unrolled sequence rather than a conventional loop. The first four arguments stay in the standard x64 registers, so the resolved service receives a normal Windows x64 call frame."}</div>
                    <div className="pt-4">{"The actual call can be direct or wrapped by dynamic tracing or performance instrumentation. All variants preserve the same service-call contract and collect the result from "}<InlineCode text={"RAX"} />{" before entering the shared exit path."}</div>
                    <ThirdHeader text={"The Win32k Conversion Path"} />
                    <div className="pt-4">{"Win32k dispatch has one important exception to ordinary bounds failure. If the service number selects the GUI descriptor but the index cannot yet be resolved, the dispatcher can call "}<InlineCode text={"PsConvertToGuiThread"} />{". A successful conversion creates any required process and thread GUI state through the session's registered Win32 callouts. The dispatcher then repeats descriptor selection and bounds checking instead of failing the original syscall immediately."}</div>
                    <div className="pt-4">{"This behavior is what allows a thread's first Win32k syscall to participate in its transition into a GUI thread. Conversion is not guaranteed: mitigation policy, process state, session state, or callback failure can reject it. If conversion fails, or if an invalid service does not qualify for this path, the syscall returns a mapped failure or "}<InlineCode text={"STATUS_INVALID_SYSTEM_SERVICE"} />{"."}</div>
                    <div className="pt-4">{"For a valid Win32k service, the dispatcher also checks the thread environment block's GDI batch count. When pending batched GDI work exists, it calls "}<InlineCode text={"PsInvokeWin32Callout"} />{" with callout ID 7 before invoking the requested service. This gives the session's Win32 callback an opportunity to flush the batch at the transition boundary. The same ID is used by an explicit GUI-thread and batch-flush helper, which is why ID 7 appears in the callback mapping later in this post."}</div>
                    <ThirdHeader text={"Returning to User Mode"} />
                    <div className="pt-4">{"After the service completes, the shared exit code distinguishes a normal user syscall from an internal kernel invocation that entered the same dispatcher. The kernel case restores the previous thread and trap-frame state and returns to its caller. The user case performs much stricter validation."}</div>
                    <div className="pt-4">{"Windows verifies that the service is not returning above passive IRQL, that APC accounting is consistent, and that the thread's previous mode still describes user mode. It delivers pending user APCs, synchronizes the user isolation domain, restores debug, floating-point, CET, and speculation-control state, and clears selected volatile registers to limit accidental disclosure of kernel state."}</div>
                    <div className="pt-4">{"The ordinary fast path restores user state with "}<InlineCode text={"SYSRET"} />{". KVA-shadow systems transfer through a dedicated exit helper that restores the user address space before returning, while exceptional or provider-specific contexts can use an "}<InlineCode text={"IRETQ"} />{"-based path. By the time control reaches user mode, the service result is in "}<InlineCode text={"RAX"} />{" and the kernel has unwound the architectural and thread state created at entry."}</div>
                    <div className="pt-4">{"For the rest of this post, the most relevant part is the junction between the Win32k conversion path, GDI batch flushing, and "}<InlineCode text={"PsInvokeWin32Callout"} />{". Syscall dispatch does not implement those session-specific operations itself. It asks the registered Win32 callback to perform them."}</div>
                    <SecondaryHeader text={"Win32 Callbacks"} />
                    <div className="pt-4"><InlineCode text={"PsWin32CallBack"} />{" and "}<InlineCode text={"PsWin32NullCallBack"} />{" are callback objects used when the executive needs Win32k to perform a session-aware operation. One place this happens is the GDI batch-flush path in "}<InlineCode text={"KiSystemCall64"} />{", which reaches them through "}<InlineCode text={"PsInvokeWin32Callout"} />{". The same mechanism is also used by process, job, object-manager, power, and session-related paths, so these callbacks are broader than syscall dispatch alone."}</div>
                    <div className="pt-4"><InlineCode text={"PsInvokeWin32Callout"} />{" is the common invocation wrapper. Its pseudocode is straightforward:"}</div>
                    <Code text={codeBlock4} language={"cpp"} />
                    <div className="pt-4">{"The function first passes the callout ID and context to "}<InlineCode text={"PspUpdateCalloutParameters"} />{". The observed control flow establishes that this helper prepares the callout arguments and can reject them; the exact meaning of every additional value was not recovered in this pass. If that setup fails, invocation stops with "}<InlineCode text={"STATUS_INVALID_PARAMETER"} />{"."}</div>
                    <div className="pt-4">{"Next, "}<InlineCode text={"PsSessionGetWin32Callouts"} />{" selects the callback registration that applies to the current process context. "}<InlineCode text={"ExReferenceCallBackBlock"} />{" takes a stable reference to the currently registered callback block, which prevents the registration from disappearing while the call is in progress. If no block can be referenced, the wrapper again returns "}<InlineCode text={"STATUS_INVALID_PARAMETER"} />{". The callback is then invoked through a Control Flow Guard-protected indirect call, its return status is preserved, and "}<InlineCode text={"ExDereferenceCallBackBlock"} />{" releases the temporary reference. In other words, "}<InlineCode text={"PsInvokeWin32Callout"} />{" handles parameter preparation and callback lifetime; the selected Win32k handler performs the operation associated with the numeric callout ID."}</div>
                    <div className="pt-4">{"The following normalized pseudocode expresses the observed selection result without preserving redundant temporary variables introduced by the decompiler:"}</div>
                    <Code text={codeBlock5} language={"cpp"} />
                    <div className="pt-4"><InlineCode text={"PsSessionGetWin32Callouts"} />{" decides whether the normal Win32k callback is valid for the current address-space context. In the ordinary case, where "}<InlineCode text={"OverrideAddressSpace"} />{" is clear, it returns "}<InlineCode text={"PsWin32CallBack"} />{". That global callback registration represents the active Win32k callout path."}</div>
                    <div className="pt-4">{"When "}<InlineCode text={"OverrideAddressSpace"} />{" is set, the current thread may be executing while attached to an address space that should not blindly inherit the normal callback context. The function therefore checks whether the process's session exposes Win32 callouts. If that session state is unavailable, it returns "}<InlineCode text={"PsWin32NullCallBack"} />{" instead of the normal registration. In this selection path, the null registration acts as the fallback for the special context: callers can use the same callback framework without dispatching through the normal session handler. If session callouts are available, the normal "}<InlineCode text={"PsWin32CallBack"} />{" registration remains usable. This selection logic establishes which callback object is chosen; by itself, it does not prove every behavior of the handler registered in the null object."}</div>
                    <div className="pt-4">{"The important distinction is that these are callback objects selected by executive state, not direct pointers to a particular Win32k service. "}<InlineCode text={"PsInvokeWin32Callout"} />{" references whichever object "}<InlineCode text={"PsSessionGetWin32Callouts"} />{" returns and invokes the handler currently registered in it. This extra layer is what makes the behavior session-aware and safe against concurrent callback registration changes."}</div>
                    <div className="pt-4">{"From this control flow, I recovered two conditions that must both be true for "}<InlineCode text={"PsSessionGetWin32Callouts"} />{" to select "}<InlineCode text={"PsWin32NullCallBack"} />{" instead of the normal "}<InlineCode text={"PsWin32CallBack"} />{" object:"}</div>
                    <NumberedList items={[{ content: <>{"The process must have "}<InlineCode text={"OverrideAddressSpace"} />{" flag set in its "}<InlineCode text={"EPROCESS"} />{"."}</> }, { content: <>{"The process's session object must have "}<InlineCode text={"Win32Callouts"} />{" set to 0."}</> }]} />
                    <ThirdHeader text={"Callouts Mapping"} />
                    <div className="pt-4">{"I then followed the references to "}<InlineCode text={"PsInvokeWin32Callout"} />{" to see where else the mechanism is used and what the callout IDs represent. This is the mapping I recovered:"}</div>
                    <BlogTable headers={[<>{"Caller"}</>, <>{"Callout ID"}</>, <>{"Meaning"}</>]} rows={[[<>{"SeCaptureAtomTableCallout"}</>, <>{"2"}</>, <>{"Captures/initializes a token/session atom-table-related Win32 object when token state requires it."}</>], [<>{"PspJobDelete"}</>, <>{"6"}</>, <>{"Job deletion / Win32k job notification fallback path."}</>], [<>{"PspSetUILimitJobObject"}</>, <>{"6"}</>, <>{"Job UI limits notification to Win32k."}</>], [<>{"PspAssignProcessToJob"}</>, <>{"6"}</>, <>{"Process assigned to job; Win32k job add-process notification fallback."}</>], [<>{"KiSystemCall64"}</>, <>{"7"}</>, <>{"Flushes pending GDI batching before dispatching a valid Win32k service."}</>], [<>{"PspEnsureGuiThreadAndBatchFlush"}</>, <>{"7"}</>, <>{"Explicit GUI-thread conversion / batch flush helper"}</>], [<>{"PspShutdownCsrProcess"}</>, <>{"0x1f"}</>, <>{"CSR process shutdown, after attaching into the target process."}</>], [<>{"NtSetSystemInformation"}</>, <>{"0x20"}</>, <>{"Specific SystemInformationClass path, uses current or referenced process session."}</>], [<>{"ExpWin32OpenProcedure"}</>, <>{"0x21"}</>, <>{"Object manager Win32 open callback path for desktop/window-station-style objects."}</>], [<>{"PspQueryProcessInterferenceCountCallback"}</>, <>{"0x18"}</>, <>{"Queries process interference count through Win32k."}</>], [<>{"PspSetProcessTimerDelayForWin32"}</>, <>{"0x29"}</>, <>{"Sends process timer-delay/session data to Win32k."}</>], [<>{"PspChangeProcessExecutionState"}</>, <>{"0x2b"}</>, <>{"Process execution-state transition, one branch."}</>], [<>{"PspChangeProcessExecutionState"}</>, <>{"0x2c"}</>, <>{"Process execution-state transition, second branch."}</>], [<>{"PopInvokeWin32CalloutWithWatchdog"}</>, <>{"variable"}</>, <>{"Power manager wrapper that invokes arbitrary Win32 callout IDs with watchdog instrumentation."}</>]]} alignments={[null, null, null]} caption={"Observed Win32 callout IDs and callers"} />
                    <div className="pt-4">{"The references support three useful conclusions:"}</div>
                    <NumberedList items={[{ content: <>{"Some callout IDs are reused across different contexts, indicating a level of abstraction in the Win32k subsystem."}</> }, { content: <>{"The callout IDs are not sequential."}</> }, { content: <>{"Callback selection affects more than syscall dispatch, so any security analysis of these objects must account for their process, job, session, object-manager, and power-management consumers."}</> }]} />
                    <SecondaryHeader text={"Conclusion"} />
                    <div className="pt-4">{"The original goal was to find a new PatchGuard bypass, and this path did not get me there. What it did produce was a much clearer model of the boundary between the executive, Win32k, and the graphics stack."}</div>
                    <div className="pt-4">{"The most interesting part for me is that the callback mechanism is not limited to one GUI syscall. "}<InlineCode text={"PsInvokeWin32Callout"} />{" provides a common, reference-counted path for operations ranging from GDI batch flushing to job and session notifications, while "}<InlineCode text={"PsSessionGetWin32Callouts"} />{" changes the selected callback when the current address-space and session state require it. The repeated callout IDs also show that the ID identifies an operation class rather than a unique caller."}</div>
                    <div className="pt-4">{"There is still much more to explore. While this post covered the basic flow from "}<InlineCode text={"win32u.dll"} />{" to "}<InlineCode text={"PsInvokeWin32Callout"} />{" and selected parts of the Win32k subsystem, many details remain undocumented. I hope you found this post interesting, learned a few new things, and are inspired to dig deeper into the inner workings of Win32k. Of course, feel free to reach out with questions and share your findings."}</div>
                </article>
            </div>
        </div>
    );
}
